// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAdjT3_fKCeOfhzpf0lKdiTUpCesu5beQ',
    appId: '1:195442640345:web:e90b5e4c1607ad7b3e85c8',
    messagingSenderId: '195442640345',
    projectId: 'mobile-teologia',
    authDomain: 'mobile-teologia.firebaseapp.com',
    storageBucket: 'mobile-teologia.firebasestorage.app',
    measurementId: 'G-56LVY40WC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_Y1jlj0l5LNkf4GJZ7zH6LztPZjqO-E',
    appId: '1:195442640345:android:31189446bc5b512f3e85c8',
    messagingSenderId: '195442640345',
    projectId: 'mobile-teologia',
    storageBucket: 'mobile-teologia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiWE7AQEEOx3bpwW7VbTmdWuV14qkr5Wg',
    appId: '1:195442640345:ios:a608eca47fa13e523e85c8',
    messagingSenderId: '195442640345',
    projectId: 'mobile-teologia',
    storageBucket: 'mobile-teologia.firebasestorage.app',
    iosBundleId: 'trsystemas.mobileTeologia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiWE7AQEEOx3bpwW7VbTmdWuV14qkr5Wg',
    appId: '1:195442640345:ios:e6cb90fecc39d93b3e85c8',
    messagingSenderId: '195442640345',
    projectId: 'mobile-teologia',
    storageBucket: 'mobile-teologia.firebasestorage.app',
    iosBundleId: 'com.trsystemas.mobileTeologia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAdjT3_fKCeOfhzpf0lKdiTUpCesu5beQ',
    appId: '1:195442640345:web:290f4d7286edec3e3e85c8',
    messagingSenderId: '195442640345',
    projectId: 'mobile-teologia',
    authDomain: 'mobile-teologia.firebaseapp.com',
    storageBucket: 'mobile-teologia.firebasestorage.app',
    measurementId: 'G-K8BWLVXG74',
  );
}
