global:
  scrape_interval: 15s  # Intervalo de coleta de métricas
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nest-backend'
    metrics_path: /api/v1/metrics  # Corrigido: caminho correto da rota de métricas
    static_configs:
      - targets: ['backend:3000']
        labels:
          app: 'teologia_backend'
          environment: 'production'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          app: 'host_metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: 'prometheus'
