global:
  scrape_interval: 15s  # Intervalo de coleta de métricas
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nest-backend'
    static_configs:
      - targets: ['backend:3000']
        labels:
          app: 'teologia_backend'
          environment: 'production'

  # Exportador de métricas do host (opcional, se você usar node_exporter)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          app: 'host_metrics'

  # Monitoramento do próprio Prometheus (útil para debug)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: 'prometheus'
