name: mobile_teologia
description: App mobile Teologia FATEAL
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  http: ^1.2.1
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.4
  # Outras dependências que você precisar (ex: lottie, shared_preferences...)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/
    - assets/sounds/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
