name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - uses: actions/checkout@v3

      # 2) Prepara SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Evita “man-in-the-middle” na primeira conexão
          ssh-keyscan -H 5.161.196.30 >> ~/.ssh/known_hosts

      # 3) Executa o deploy
      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 root@5.161.196.30 << 'EOF'
            set -e                                          # aborta em erro
            cd /var/www/TEOLOGIA_FATEAL

            echo "→ Git pull"
            git pull origin main

            echo "→ Instalando dependências"
            cd backend_teologia
            yarn install --production                       # só deps prod

            echo "→ Build"
            yarn build

            echo "→ Reiniciando PM2"
            pm2 restart teologia-backend || pm2 start dist/src/main.js --name teologia-backend

            echo "✓ Deploy concluído"
          EOF
